--
-- PostgreSQL database dump
--

-- Dumped from database version 10.5 (Debian 10.5-1.pgdg90+1)
-- Dumped by pg_dump version 10.5 (Debian 10.5-1.pgdg90+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: Category; Type: TABLE; Schema: public; Owner: or-user
--

CREATE TABLE public."Category" (
    id bigint NOT NULL,
    name text NOT NULL
);


ALTER TABLE public."Category" OWNER TO "or-user";

--
-- Name: Category_id_seq; Type: SEQUENCE; Schema: public; Owner: or-user
--

ALTER TABLE public."Category" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MenuItem; Type: TABLE; Schema: public; Owner: or-user
--

CREATE TABLE public."MenuItem" (
    id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    price double precision NOT NULL,
    category text NOT NULL,
    image_url jsonb NOT NULL
);


ALTER TABLE public."MenuItem" OWNER TO "or-user";

--
-- Name: MenuItem_id_seq; Type: SEQUENCE; Schema: public; Owner: or-user
--

ALTER TABLE public."MenuItem" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MenuItem_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fluent; Type: TABLE; Schema: public; Owner: or-user
--

CREATE TABLE public.fluent (
    id uuid NOT NULL,
    name text NOT NULL,
    batch bigint NOT NULL,
    "createdAt" timestamp without time zone,
    "updatedAt" timestamp without time zone
);


ALTER TABLE public.fluent OWNER TO "or-user";

--
-- Data for Name: Category; Type: TABLE DATA; Schema: public; Owner: or-user
--

COPY public."Category" (id, name) FROM stdin;
1	appetizers
2	entrees
3	specials
4	drinks
5	desserts
\.


--
-- Data for Name: MenuItem; Type: TABLE DATA; Schema: public; Owner: or-user
--

COPY public."MenuItem" (id, name, description, price, category, image_url) FROM stdin;
2	Margherita Pizza	Tomato sauce, fresh mozzarella, basil, and extra-virgin olive oil.	10	entrees	{"relative": "http://localhost:8090/images/margherita-pizza.jpg"}
3	Grilled Steelhead Trout Sandwich	Pacific steelhead trout with lettuce, tomato, and red onion.	9	entrees	{"relative": "http://localhost:8090/images/grilled-steelhead-trout-sandwich.jpg"}
4	Pesto Linguini	Stewed sliced beef with yellow onions and garlic in a vinegar-soy sauce. Served with steamed jasmine rice and sautéed vegetables.	9	entrees	{"relative": "http://localhost:8090/images/pesto-linguini.jpg"}
6	Italian Salad	Garlic, red onions, tomatoes, mushrooms, and olives on top of romaine lettuce."	5	appetizers	{"relative": "http://localhost:8090/images/italian-salad.jpg"}
1	Spaghetti and Meatballs	Seasoned meatballs on top of freshly-made spaghetti. Served with a robust tomato sauce.	9	entrees	{"relative": "http://localhost:8090/images/spaghetti-and-meatballs.jpg"}
5	Chicken Noodle Soup	Delicious chicken simmered alongside yellow onions, carrots, celery, and bay leaves, chicken stock.	3	appetizers	{"relative": "http://localhost:8090/images/chicken-noodle-soup.jp2"}
\.


--
-- Data for Name: fluent; Type: TABLE DATA; Schema: public; Owner: or-user
--

COPY public.fluent (id, name, batch, "createdAt", "updatedAt") FROM stdin;
b4f4c12d-d63a-403f-9c8e-bd3f5d291288	MenuItem	1	2018-09-09 12:45:55.338886	2018-09-09 12:45:55.338886
2487e294-6c17-4874-8572-adec339948c1	Category	1	2018-09-09 12:45:55.34676	2018-09-09 12:45:55.34676
\.


--
-- Name: Category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: or-user
--

SELECT pg_catalog.setval('public."Category_id_seq"', 5, true);


--
-- Name: MenuItem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: or-user
--

SELECT pg_catalog.setval('public."MenuItem_id_seq"', 6, true);


--
-- Name: Category pk:Category.id; Type: CONSTRAINT; Schema: public; Owner: or-user
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "pk:Category.id" PRIMARY KEY (id);


--
-- Name: MenuItem pk:MenuItem.id; Type: CONSTRAINT; Schema: public; Owner: or-user
--

ALTER TABLE ONLY public."MenuItem"
    ADD CONSTRAINT "pk:MenuItem.id" PRIMARY KEY (id);


--
-- Name: fluent pk:fluent.id; Type: CONSTRAINT; Schema: public; Owner: or-user
--

ALTER TABLE ONLY public.fluent
    ADD CONSTRAINT "pk:fluent.id" PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

